### ISSUE TITLE
How to add XML attribute to custom control function name, e.g. <reverse_arpayment key="1234">

### ISSUE THREAD

**Issue by arjunshukla** [GoodwayGroup/intacct-api#14]
https://developer.intacct.com/api/accounts-receivable/ar-payments/#reverse-ar-payment-legacy

**Comment by mrlannigan** [comment]
Hello @arjunshukla,

Sorry for the delay in responding, but to create this request see the following:
```javascript
import { ControlFunction } from 'intacct-api';

const theFunction = new ControlFunction('reverse_arpayment', {
    '@key': 1234,
    datereversed: {
        year: 2017,
        month: 10,
        day: 16
    }
});
```

This module uses [xmlbuilder](https://www.npmjs.com/package/xmlbuilder) to create the requests that are sent to Intacct. Please see [this documentation](https://github.com/oozcitak/xmlbuilder-js/wiki/Conversion-From-Object) on how it converts your JS objects into XML.
